# This will build the repo and upload the package as an artifact

name: Build DiskLib

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '17' ] # LTS versions

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Extract Maven project version
      run: echo "lib_version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_ENV
      id: project
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      if: ${{ matrix.java == '8' }}
      with:
        name: DiskLib-${{ env.lib_version }}-SNAPSHOT
        path: target/DiskLib-${{ env.lib_version }}.jar
        retention-days: 90
